//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerWeb.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrawlerDataContext : DbContext
    {
        public CrawlerDataContext()
            : base("name=CrawlerDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppSite> AppSites { get; set; }
        public virtual DbSet<SearchEntry> SearchEntries { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TaggedEntry> TaggedEntries { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<SiteUser> SiteUsers { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
