//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchEntry()
        {
            this.TaggedEntries = new HashSet<TaggedEntry>();
        }
    
        public int EntryID { get; set; }
        public string URL { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> EntryTimestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaggedEntry> TaggedEntries { get; set; }
    }
}
