//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaggedEntry
    {
        public int TagID { get; set; }
        public int EntryID { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual SearchEntry SearchEntry { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
