//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public int TermID { get; set; }
        public Nullable<int> TagID { get; set; }
        public string TermText { get; set; }
    
        public virtual Tag Tag { get; set; }
    }
}
